# Generated by Django 5.0.4 on 2024-05-31 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pizza', '0002_rename_precog_pizza_preco_remove_pizza_precom_and_more'),
        ('usuario', '0005_delete_pizza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('valorTotal', models.FloatField()),
                ('quantidadeTotal', models.IntegerField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pizzas', models.ManyToManyField(to='pizza.pizza')),
            ],
        ),
    ]
