# Generated by Django 5.0.4 on 2024-05-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0002_alter_carrinho_quantidadetotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='quantidadeTotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='valorTotal',
            field=models.FloatField(default=0),
        ),
    ]
