# Generated by Django 5.0.4 on 2024-06-01 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0007_remove_carrinho_id_alter_carrinho_usuario'),
        ('pizza', '0002_rename_precog_pizza_preco_remove_pizza_precom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='pizzas',
        ),
        migrations.CreateModel(
            name='ItemDeCarrinho',
            fields=[
                ('quantidade', models.IntegerField()),
                ('pizza', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pizza.pizza')),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrinho.carrinho')),
            ],
        ),
    ]
