# Generated by Django 5.0.4 on 2024-05-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_customuser_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo',
            field=models.CharField(choices=[('A', 'Administrador'), ('B', 'Usuário')], default='B', max_length=1),
        ),
    ]
