# Generated by Django 5.0.4 on 2024-05-30 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_pizza'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pizza',
        ),
    ]
