# Generated by Django 5.0.4 on 2024-06-02 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_delete_pizza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rua', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=80)),
                ('numero', models.IntegerField()),
            ],
        ),
    ]
