# Generated by Django 5.0.4 on 2024-06-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendas_diarias', models.IntegerField(default=0)),
                ('lucro_diario', models.FloatField(default=0)),
                ('vendas_totais', models.IntegerField(default=0)),
                ('lucro_total', models.FloatField(default=0)),
            ],
        ),
    ]
