# Generated by Django 5.0.4 on 2024-06-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_rename_precog_pizza_preco_remove_pizza_precom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='imagem',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
    ]
