# Generated by Django 5.0.4 on 2024-06-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_alter_pizza_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='imagem',
            field=models.ImageField(max_length=255, upload_to='images/'),
        ),
    ]
