# Generated by Django 5.0.4 on 2024-06-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo_pagamento',
            field=models.CharField(default='fisico', max_length=30),
        ),
    ]
