# Generated by Django 5.0.4 on 2024-06-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0002_pedido_tipo_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='quantidadeTotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valorTotal',
            field=models.FloatField(default=0),
        ),
    ]
